In [44]:
num=int(input("Enter the number: "))

Enter the number:  2


In [18]:
num*=num
print(num)

4


In [19]:
#create a dictionary with your details and print
dict={'Name':['Princy'],
      'Age':[22],
      'Course':['MCA']}
print (dict)

{'Name': ['Princy'], 'Age': [22], 'Course': ['MCA']}


In [20]:
import numpy as np  #np is the alias of numpy

In [21]:
list=[1,2,3,4,5,6,7,8]  #declaration of list
npArray=np.array(list)  #converting list to array
print(list)

[1, 2, 3, 4, 5, 6, 7, 8]


In [22]:
print(npArray)

[1 2 3 4 5 6 7 8]


In [23]:
print(npArray.dtype)

int64


In [24]:
#finding mean of np array
mean=np.mean(npArray)
print("mean of array is: ",mean)

mean of array is:  4.5


In [25]:
#finding median of np array
median=np.median(npArray)
print("median of array is: ",median)

median of array is:  4.5


In [26]:
ulist=[12,6,34,78,21,9,2,5]
uarr=np.array(ulist)
print("Uarr is ",uarr)

Uarr is  [12  6 34 78 21  9  2  5]


In [27]:
#SORTING
sarr=np.sort(uarr)
print("sarr is ",sarr)

sarr is  [ 2  5  6  9 12 21 34 78]


In [28]:
#descending order
dsarr=np.sort(uarr)[::-1]
print(dsarr)

[78 34 21 12  9  6  5  2]


In [29]:
#Conversion of 1D array to 2D
uarr2d=np.reshape(uarr,(2,4))
print(uarr2d)

[[12  6 34 78]
 [21  9  2  5]]


In [30]:
direct=np.array([1,2,3,4,5,6])
print(direct)

[1 2 3 4 5 6]


In [31]:
print(direct[3])

4


In [32]:
print(direct[2:])

[3 4 5 6]


In [33]:
print(direct[:4])

[1 2 3 4]


In [34]:
a2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(a2d[::-1 ,3:1:-1])  

[[9]
 [6]
 [3]]


In [36]:
print(a2d[a2d>5])

[6 7 8 9]


In [46]:
s1=np.array([20,30,40,50,60])
s2=np.array([15,25,35,45,55])
sarr=np.add(s1,s2)
print(sarr)

[ 35  55  75  95 115]


In [38]:
sarrMean=np.mean(sarr)
print(sarrMean)

75.0


In [39]:
min=sarr.min()
max=sarr.max()
print(min,max)

35 115


In [40]:
min2d=a2d.min()
print(min2d)

1


In [41]:
c=a2d[: ,2].min()
print(c)

3


In [42]:
r=a2d[1,:].min()
print(r)

4


In [43]:
data=np.loadtxt('august.txt',dtype=str,usecols=(0,2))
print(data)
#val=[7,8,9]
#np.savetxt('august.txt',val,delimiter=',')

[['a' 'c']
 ['1' '34']]
