In [1]:
import numpy as np

In [2]:
scores=np.array([[85,90,78],
                 [92,88,95],
                 [76,95,85],
                 [90,85,92],
                 [88,76,89]])

In [3]:
#MEAN SCORES OF EACH SUBJECT
meanmaths=np.mean(scores[: ,0])
print("Mean score of maths=",meanmaths)
meanscience=np.mean(scores[: ,1])
print("Mean score of science=",meanscience)
meanenglish=np.mean(scores[: ,2])
print("Mean score of english=",meanenglish)

Mean score of maths= 86.2
Mean score of science= 86.8
Mean score of english= 87.8


In [4]:
#MEDIAN SCORES OF EACH SUBJECT
medianmaths=np.median(scores[: ,0])
print("Median score of maths=",medianmaths)
medianscience=np.median(scores[: ,1])
print("Median score of science=",medianscience)
medianenglish=np.median(scores[: ,2])
print("Median score of english=",medianenglish)

Median score of maths= 88.0
Median score of science= 88.0
Median score of english= 89.0


In [5]:
#minimum scores in each subject
min1=scores[: ,0].min()
print("Minimum score in maths",min1)
min2=scores[: ,1].min()
print("Minimum score in science",min2)
min3=scores[: ,2].min()
print("Minimum score in english",min3)

Minimum score in maths 76
Minimum score in science 76
Minimum score in english 78


In [6]:
#maximum scores in each subject
max1=scores[: ,0].max()
print("Max score in maths",max1)
max2=scores[: ,1].max()
print("Max score in science",max2)
max3=scores[: ,2].min()
print("Max score in english",max3)

Max score in maths 92
Max score in science 95
Max score in english 78


In [7]:
#Sorted scores of each subject
s1=np.sort(scores[: ,0])
print("Sorted scores of maths",s1)
s2=np.sort(scores[: ,1])
print("Sorted scores of science",s2)
s3=np.sort(scores[: ,2])
print("Sorted scores of english",s3)

Sorted scores of maths [76 85 88 90 92]
Sorted scores of science [76 85 88 90 95]
Sorted scores of english [78 85 89 92 95]


In [13]:
scores

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [12]:
#sum of marks of all the subjects of each student and the maximum total marks
lis = []
for i in range(0,5):
    sum1 = np.sum(scores[i,:])
    lis.append(sum1)
    
for i in range(0,5):
    print("Total marks of Student ",i+1)
    print(lis[i])
      

print("\nMaximum marks= ",int(max(lis)))

Total marks of Student  1
253
Total marks of Student  2
275
Total marks of Student  3
256
Total marks of Student  4
267
Total marks of Student  5
253

Maximum marks=  275


In [9]:
#Converting a 5x3 matrix to 3x5 matrix
t=np.transpose(scores)
print("Transpose of the matrix is\n",t)

Transpose of the matrix is
 [[85 92 76 90 88]
 [90 88 95 85 76]
 [78 95 85 92 89]]
